// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOBASqcrJ2CJmhOxxIULkWIJc1hP1yiB4',
    appId: '1:204340310004:web:80d2f91d55b2f113a913a1',
    messagingSenderId: '204340310004',
    projectId: 'turns-ccc9e',
    authDomain: 'turns-ccc9e.firebaseapp.com',
    storageBucket: 'turns-ccc9e.firebasestorage.app',
    measurementId: 'G-CGXYPYKY14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ5pjBe_d2dzLaCppTluvy8jV2UGetivg',
    appId: '1:204340310004:android:ce987a17d01a24d1a913a1',
    messagingSenderId: '204340310004',
    projectId: 'turns-ccc9e',
    storageBucket: 'turns-ccc9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOhMlOwZ0-M0bjn2NIfwNG_krGJ8PvTKg',
    appId: '1:204340310004:ios:acc0ed8c4eca4c0da913a1',
    messagingSenderId: '204340310004',
    projectId: 'turns-ccc9e',
    storageBucket: 'turns-ccc9e.firebasestorage.app',
    iosClientId: '204340310004-le4d7qtg7mbh4pofvcqtuqcidkpolseg.apps.googleusercontent.com',
    iosBundleId: 'com.ingenio.turns.turnsFlutter',
  );
}
